name: 'Black Duck scan and publish to Platform'
description: 'Runs Black Duck SCA scan to detect vulnerabilities, risks, and policy violations, and publishes to the CloudBees platform.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  server-url:
    description: The URL of the Black Duck server
    required: true
  api-token:
    description: The API token for Black Duck
    required: true
  cloudbees-url: 
    description: Cloudbees API URL
    required: false
    default: "https://api.cloudbees.io"
  project-name:
    description: The name of the project to scan
    required: false
    default: ''
  project-version:
    description: The version of the project to scan
    required: false
    default: ''
  detect-cli-params:
    description: Additional parameters for the Detect CLI
    required: false
    default: ''
  ref:
    description: 'Flag to indicate the ref that should be archived (same as supplied to checkout)'
    required: false
    default: ''
  workspace-dir:
    description: 'Flag to mention the path where the checked out code will be present'
    required: false
    default: ''
  scan-mode:
    description: 'Flag to mention the scan mode'
    required: false
    default: 'INTELLIGENT'
  step-id:
    description: 'The ID of the step in the workflow'
    required: false
    default: ''
outputs:
  critical-count:
    description: A string containing the number of Critical security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.critical-count}}
  very-high-count:
    description: A string containing the number of Very High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.very-high-count}}
  high-count:
    description: A string containing the number of High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.high-count}}
  medium-count:
    description: A string containing the number of Medium security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.medium-count}}
  low-count:
    description: A string containing the number of Low security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.low-count}}

runs:
  using: "composite"
  steps:

    - name: Create tar of source code
      shell: bash
      run: |
        tar -cvf output.tar .

    - name: Create request JSON file in workspace
      shell: bash
      run: |
        FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
        mkdir -p "$(dirname "$FILE_PATH")"
        touch "$FILE_PATH"
        echo "File created at: $FILE_PATH"


    - name: Generate reference files 
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="$GITHUB_WORKFLOW_REF" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:984156a62f4ed484f0c337135c30f8a64e95b523 \
          generate-references --asset-type "CODE"

    - name: Run blackduck compliance plugin
      shell: bash
      run: |
        docker run --rm \
          -u root \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e RUN_ID="${{ github.run_id }}" \
          -e JOB_ID="${{ github.job }}" \
          -e STEP_ID="${{ inputs.step-id }}" \
          -e BLACKDUCK_URL=${{ inputs.server-url }} \
          -e BLACKDUCK_API_TOKEN=${{ inputs.api-token }} \
          -e BLACKDUCK_PROJECT="${{ inputs.project-name }}" \
          -e BLACKDUCK_PROJECT_VERSION="${{ inputs.project-version }}" \
          -e BLACKDUCK_SCAN_MODE="${{ inputs.scan-mode }}" \
          -e BLACKDUCK_DETECT_CLI_PARAMS="${{ inputs.detect-cli-params }}" \
          public.ecr.aws/l7o7z1g8/actions/plugin-blackduck-sca:54d03a70c3e1326f0a860f92aa8ac724455c97c7 \
          --mode single

    - id: process-outputs
      name: Complete execution plan
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="$GITHUB_WORKFLOW_REF" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:984156a62f4ed484f0c337135c30f8a64e95b523 \
          process-outputs
